[book]
authors = ["Mimic Project"]
language = "en"
multilingual = false
src = "src"
title = "MIMIC Documentation"

[build]
build-dir = "book"

[output.html]
theme = "theme"
additional-css = ["theme/css/general.css"]
git-repository-url = "https://github.com/aegion-dynamic/mimic-docs-Docs"
logo = "logo.svg"

[output.html.search]
limit-results = 30
copy-js = true
