#!/usr/bin/env python3
"""
UART Code Generator for STM32 HAL Projects
Generates complete UART initialization and frame handling code.

Author: Mimic Project
"""

import os
import sys
from dataclasses import dataclass
from enum import Enum
from typing import Optional


class Parity(Enum):
    NONE = "NONE"
    EVEN = "EVEN"
    ODD = "ODD"


class StopBits(Enum):
    ONE = "1"
    TWO = "2"


class FrameType(Enum):
    TEXT = "TEXT"
    COMMAND = "COMMAND"
    BINARY = "BINARY"


@dataclass
class UARTConfig:
    """UART Configuration Parameters"""
    uart_instance: str = "USART2"
    baud_rate: int = 9600
    parity: Parity = Parity.NONE
    stop_bits: StopBits = StopBits.ONE
    frame_type: FrameType = FrameType.TEXT
    binary_frame_length: int = 16  # For BINARY frame type
    text_delimiter: str = "\\n"    # For TEXT frame type
    max_buffer_size: int = 128


class UARTCodeGenerator:
    """Generates STM32 HAL UART code based on configuration"""
    
    def __init__(self, config: UARTConfig):
        self.config = config
        self.handle_name = f"h{config.uart_instance.lower()}"
        
    def _get_hal_parity(self) -> str:
        mapping = {
            Parity.NONE: "UART_PARITY_NONE",
            Parity.EVEN: "UART_PARITY_EVEN",
            Parity.ODD: "UART_PARITY_ODD"
        }
        return mapping[self.config.parity]
    
    def _get_hal_stopbits(self) -> str:
        mapping = {
            StopBits.ONE: "UART_STOPBITS_1",
            StopBits.TWO: "UART_STOPBITS_2"
        }
        return mapping[self.config.stop_bits]
    
    def _get_word_length(self) -> str:
        # If parity is enabled, we need 9 bits to have 8 data bits
        if self.config.parity != Parity.NONE:
            return "UART_WORDLENGTH_9B"
        return "UART_WORDLENGTH_8B"

    # =========================================================================
    # HEADER FILE GENERATION
    # =========================================================================
    
    def generate_usart_h(self) -> str:
        """Generate usart.h header file"""
        instance = self.config.uart_instance
        handle = self.handle_name
        
        code = f'''/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file    usart.h
  * @brief   UART Configuration Header - Auto-generated by UART_Generator
  ******************************************************************************
  */
/* USER CODE END Header */

#ifndef __USART_H__
#define __USART_H__

#ifdef __cplusplus
extern "C" {{
#endif

/* Includes ------------------------------------------------------------------*/
#include "main.h"

/* ========================== CONFIGURATION ================================= */
#define UART_INSTANCE         {instance}
#define UART_BAUD_RATE        {self.config.baud_rate}
#define UART_MAX_BUFFER_SIZE  {self.config.max_buffer_size}
'''

        # Frame-specific defines
        if self.config.frame_type == FrameType.TEXT:
            code += f'''
/* Text Frame Configuration */
#define FRAME_TYPE_TEXT       1
#define TEXT_DELIMITER        '{self.config.text_delimiter}'
'''
        elif self.config.frame_type == FrameType.COMMAND:
            code += '''
/* Command Frame (TLV) Configuration */
#define FRAME_TYPE_COMMAND    1
#define FRAME_STX             0x02
#define FRAME_ETX             0x03
#define FRAME_MAX_DATA_LEN    64
'''
        else:  # BINARY
            code += f'''
/* Binary Frame Configuration */
#define FRAME_TYPE_BINARY     1
#define BINARY_FRAME_LENGTH   {self.config.binary_frame_length}
'''

        code += f'''
/* ========================== DATA STRUCTURES =============================== */

/* UART State Machine States */
typedef enum {{
    UART_STATE_IDLE = 0,
    UART_STATE_RECEIVING,
'''
        if self.config.frame_type == FrameType.COMMAND:
            code += '''    UART_STATE_GOT_STX,
    UART_STATE_GOT_CMD,
    UART_STATE_GOT_LEN,
    UART_STATE_GOT_DATA,
    UART_STATE_GOT_CRC,
'''
        code += '''    UART_STATE_COMPLETE,
    UART_STATE_ERROR
} UART_StateTypeDef;

'''
        if self.config.frame_type == FrameType.COMMAND:
            code += '''/* Command Frame Structure */
typedef struct {
    uint8_t cmd;
    uint8_t len;
    uint8_t data[FRAME_MAX_DATA_LEN];
    uint8_t crc;
    uint8_t valid;
} UART_CommandFrame_t;

'''

        code += f'''/* UART Receive Buffer Structure */
typedef struct {{
    uint8_t buffer[UART_MAX_BUFFER_SIZE];
    uint16_t index;
    uint16_t length;
    UART_StateTypeDef state;
    uint8_t frame_ready;
'''
        if self.config.frame_type == FrameType.COMMAND:
            code += '    UART_CommandFrame_t frame;\n'
        code += '''} UART_RxBuffer_t;

/* ========================== EXTERN VARIABLES ============================== */
'''
        code += f'''extern UART_HandleTypeDef {handle};
extern UART_RxBuffer_t uart_rx;

/* ========================== FUNCTION PROTOTYPES =========================== */

/* Initialization */
void MX_{instance}_UART_Init(void);

/* Non-blocking receive (call in main loop) */
void UART_Process(void);

/* Check if frame is ready */
uint8_t UART_IsFrameReady(void);

/* Get received data */
uint8_t* UART_GetData(uint16_t *length);

/* Clear receive buffer after processing */
void UART_ClearBuffer(void);

/* Transmit functions */
HAL_StatusTypeDef UART_Transmit(uint8_t *data, uint16_t len);
HAL_StatusTypeDef UART_TransmitString(const char *str);
'''
        if self.config.frame_type == FrameType.COMMAND:
            code += '''
/* Command frame functions */
HAL_StatusTypeDef UART_SendCommand(uint8_t cmd, uint8_t *data, uint8_t len);
UART_CommandFrame_t* UART_GetCommandFrame(void);
'''

        code += '''
/* CRC calculation */
uint8_t UART_CalculateCRC(uint8_t *data, uint16_t len);

#ifdef __cplusplus
}
#endif

#endif /* __USART_H__ */
'''
        return code

    # =========================================================================
    # SOURCE FILE GENERATION
    # =========================================================================
    
    def generate_usart_c(self) -> str:
        """Generate usart.c source file"""
        instance = self.config.uart_instance
        handle = self.handle_name
        
        code = f'''/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file    usart.c
  * @brief   UART Driver Implementation - Auto-generated by UART_Generator
  ******************************************************************************
  */
/* USER CODE END Header */

/* Includes ------------------------------------------------------------------*/
#include "usart.h"
#include <string.h>

/* ========================== PRIVATE VARIABLES ============================= */

UART_HandleTypeDef {handle};
UART_RxBuffer_t uart_rx;

/* ========================== INITIALIZATION ================================ */

/**
  * @brief {instance} Initialization Function
  * @param None
  * @retval None
  */
void MX_{instance}_UART_Init(void)
{{
    {handle}.Instance = {instance};
    {handle}.Init.BaudRate = {self.config.baud_rate};
    {handle}.Init.WordLength = {self._get_word_length()};
    {handle}.Init.StopBits = {self._get_hal_stopbits()};
    {handle}.Init.Parity = {self._get_hal_parity()};
    {handle}.Init.Mode = UART_MODE_TX_RX;
    {handle}.Init.HwFlowCtl = UART_HWCONTROL_NONE;
    {handle}.Init.OverSampling = UART_OVERSAMPLING_16;
    
    if (HAL_UART_Init(&{handle}) != HAL_OK)
    {{
        Error_Handler();
    }}
    
    /* Initialize RX buffer */
    memset(&uart_rx, 0, sizeof(UART_RxBuffer_t));
    uart_rx.state = UART_STATE_IDLE;
}}

/* ========================== CRC CALCULATION =============================== */

/**
  * @brief Calculate simple XOR CRC
  * @param data: pointer to data buffer
  * @param len: length of data
  * @retval CRC value
  */
uint8_t UART_CalculateCRC(uint8_t *data, uint16_t len)
{{
    uint8_t crc = 0;
    for (uint16_t i = 0; i < len; i++)
    {{
        crc ^= data[i];
    }}
    return crc;
}}

/* ========================== RECEIVE PROCESSING ============================ */

'''
        # Generate frame-specific receive logic
        if self.config.frame_type == FrameType.TEXT:
            code += self._generate_text_receive(handle)
        elif self.config.frame_type == FrameType.COMMAND:
            code += self._generate_command_receive(handle)
        else:
            code += self._generate_binary_receive(handle)
        
        # Common functions
        code += f'''
/* ========================== HELPER FUNCTIONS ============================== */

/**
  * @brief Check if a complete frame has been received
  * @retval 1 if frame ready, 0 otherwise
  */
uint8_t UART_IsFrameReady(void)
{{
    return uart_rx.frame_ready;
}}

/**
  * @brief Get pointer to received data
  * @param length: pointer to store data length
  * @retval pointer to data buffer
  */
uint8_t* UART_GetData(uint16_t *length)
{{
    if (length != NULL)
    {{
        *length = uart_rx.length;
    }}
    return uart_rx.buffer;
}}

/**
  * @brief Clear receive buffer after processing
  */
void UART_ClearBuffer(void)
{{
    uart_rx.index = 0;
    uart_rx.length = 0;
    uart_rx.frame_ready = 0;
    uart_rx.state = UART_STATE_IDLE;
    memset(uart_rx.buffer, 0, UART_MAX_BUFFER_SIZE);
'''
        if self.config.frame_type == FrameType.COMMAND:
            code += '    memset(&uart_rx.frame, 0, sizeof(UART_CommandFrame_t));\n'
        code += '''}

/* ========================== TRANSMIT FUNCTIONS ============================ */

/**
  * @brief Transmit data via UART (non-blocking style with short timeout)
  * @param data: pointer to data buffer
  * @param len: length of data
  * @retval HAL status
  */
HAL_StatusTypeDef UART_Transmit(uint8_t *data, uint16_t len)
{{
'''
        code += f'    return HAL_UART_Transmit(&{handle}, data, len, 100);\n'
        code += '''}

/**
  * @brief Transmit null-terminated string
  * @param str: pointer to string
  * @retval HAL status
  */
HAL_StatusTypeDef UART_TransmitString(const char *str)
{
    return UART_Transmit((uint8_t*)str, strlen(str));
}
'''
        
        if self.config.frame_type == FrameType.COMMAND:
            code += self._generate_command_transmit(handle)
        
        code += '''
/* ========================== END OF FILE =================================== */
'''
        return code

    def _generate_text_receive(self, handle: str) -> str:
        """Generate text-based frame receive logic"""
        delimiter = self.config.text_delimiter
        return f'''/**
  * @brief Process UART receive - Text Frame Mode
  * @note  Call this function repeatedly in main loop
  *        Frames are delimited by '{delimiter}'
  */
void UART_Process(void)
{{
    uint8_t rx_byte;
    
    /* Already have a complete frame? Wait for processing */
    if (uart_rx.frame_ready)
    {{
        return;
    }}
    
    /* Try to receive one byte (non-blocking, 1ms timeout) */
    if (HAL_UART_Receive(&{handle}, &rx_byte, 1, 1) == HAL_OK)
    {{
        uart_rx.state = UART_STATE_RECEIVING;
        
        /* Check for delimiter */
        if (rx_byte == '{delimiter}' || rx_byte == '\\r')
        {{
            /* Frame complete */
            uart_rx.buffer[uart_rx.index] = '\\0';  /* Null terminate */
            uart_rx.length = uart_rx.index;
            uart_rx.frame_ready = 1;
            uart_rx.state = UART_STATE_COMPLETE;
        }}
        else
        {{
            /* Store byte if buffer not full */
            if (uart_rx.index < UART_MAX_BUFFER_SIZE - 1)
            {{
                uart_rx.buffer[uart_rx.index++] = rx_byte;
            }}
            else
            {{
                /* Buffer overflow - reset */
                uart_rx.index = 0;
                uart_rx.state = UART_STATE_ERROR;
            }}
        }}
    }}
}}
'''

    def _generate_command_receive(self, handle: str) -> str:
        """Generate TLV command frame receive logic (FSM)"""
        return f'''/**
  * @brief Process UART receive - Command Frame Mode (TLV)
  * @note  Frame format: [STX][CMD][LEN][DATA...][CRC][ETX]
  *        Call this function repeatedly in main loop
  */
void UART_Process(void)
{{
    uint8_t rx_byte;
    
    /* Already have a complete frame? Wait for processing */
    if (uart_rx.frame_ready)
    {{
        return;
    }}
    
    /* Try to receive one byte (non-blocking, 1ms timeout) */
    if (HAL_UART_Receive(&{handle}, &rx_byte, 1, 1) != HAL_OK)
    {{
        return;
    }}
    
    /* State machine for frame parsing */
    switch (uart_rx.state)
    {{
        case UART_STATE_IDLE:
            /* Looking for STX */
            if (rx_byte == FRAME_STX)
            {{
                uart_rx.state = UART_STATE_GOT_STX;
                uart_rx.index = 0;
                memset(&uart_rx.frame, 0, sizeof(UART_CommandFrame_t));
            }}
            break;
            
        case UART_STATE_GOT_STX:
            /* Got CMD byte */
            uart_rx.frame.cmd = rx_byte;
            uart_rx.state = UART_STATE_GOT_CMD;
            break;
            
        case UART_STATE_GOT_CMD:
            /* Got LEN byte */
            uart_rx.frame.len = rx_byte;
            if (rx_byte > FRAME_MAX_DATA_LEN)
            {{
                /* Invalid length - reset */
                uart_rx.state = UART_STATE_IDLE;
            }}
            else if (rx_byte == 0)
            {{
                /* No data, expect CRC next */
                uart_rx.state = UART_STATE_GOT_DATA;
            }}
            else
            {{
                uart_rx.state = UART_STATE_GOT_LEN;
                uart_rx.index = 0;
            }}
            break;
            
        case UART_STATE_GOT_LEN:
            /* Receiving DATA bytes */
            uart_rx.frame.data[uart_rx.index++] = rx_byte;
            if (uart_rx.index >= uart_rx.frame.len)
            {{
                uart_rx.state = UART_STATE_GOT_DATA;
            }}
            break;
            
        case UART_STATE_GOT_DATA:
            /* Got CRC byte */
            uart_rx.frame.crc = rx_byte;
            uart_rx.state = UART_STATE_GOT_CRC;
            break;
            
        case UART_STATE_GOT_CRC:
            /* Expecting ETX */
            if (rx_byte == FRAME_ETX)
            {{
                /* Validate CRC */
                uint8_t calc_crc = uart_rx.frame.cmd ^ uart_rx.frame.len;
                calc_crc ^= UART_CalculateCRC(uart_rx.frame.data, uart_rx.frame.len);
                
                if (calc_crc == uart_rx.frame.crc)
                {{
                    uart_rx.frame.valid = 1;
                    uart_rx.frame_ready = 1;
                    uart_rx.state = UART_STATE_COMPLETE;
                    
                    /* Copy data to buffer for compatibility */
                    memcpy(uart_rx.buffer, uart_rx.frame.data, uart_rx.frame.len);
                    uart_rx.length = uart_rx.frame.len;
                }}
                else
                {{
                    /* CRC error */
                    uart_rx.state = UART_STATE_ERROR;
                }}
            }}
            else
            {{
                /* Invalid ETX */
                uart_rx.state = UART_STATE_ERROR;
            }}
            
            /* Reset on error */
            if (uart_rx.state == UART_STATE_ERROR)
            {{
                uart_rx.state = UART_STATE_IDLE;
            }}
            break;
            
        default:
            uart_rx.state = UART_STATE_IDLE;
            break;
    }}
}}

/**
  * @brief Get pointer to parsed command frame
  * @retval pointer to command frame structure
  */
UART_CommandFrame_t* UART_GetCommandFrame(void)
{{
    return &uart_rx.frame;
}}
'''

    def _generate_binary_receive(self, handle: str) -> str:
        """Generate fixed-length binary frame receive logic"""
        return f'''/**
  * @brief Process UART receive - Binary Frame Mode
  * @note  Fixed frame length: {self.config.binary_frame_length} bytes
  *        Call this function repeatedly in main loop
  */
void UART_Process(void)
{{
    uint8_t rx_byte;
    
    /* Already have a complete frame? Wait for processing */
    if (uart_rx.frame_ready)
    {{
        return;
    }}
    
    /* Try to receive one byte (non-blocking, 1ms timeout) */
    if (HAL_UART_Receive(&{handle}, &rx_byte, 1, 1) == HAL_OK)
    {{
        uart_rx.state = UART_STATE_RECEIVING;
        
        /* Store byte */
        uart_rx.buffer[uart_rx.index++] = rx_byte;
        
        /* Check if frame complete */
        if (uart_rx.index >= BINARY_FRAME_LENGTH)
        {{
            uart_rx.length = BINARY_FRAME_LENGTH;
            uart_rx.frame_ready = 1;
            uart_rx.state = UART_STATE_COMPLETE;
        }}
    }}
}}
'''

    def _generate_command_transmit(self, handle: str) -> str:
        """Generate command frame transmit function"""
        return f'''
/**
  * @brief Send a command frame
  * @param cmd: command byte
  * @param data: pointer to data (can be NULL if len=0)
  * @param len: data length
  * @retval HAL status
  */
HAL_StatusTypeDef UART_SendCommand(uint8_t cmd, uint8_t *data, uint8_t len)
{{
    uint8_t frame[FRAME_MAX_DATA_LEN + 5];
    uint8_t idx = 0;
    uint8_t crc;
    
    if (len > FRAME_MAX_DATA_LEN)
    {{
        return HAL_ERROR;
    }}
    
    /* Build frame */
    frame[idx++] = FRAME_STX;
    frame[idx++] = cmd;
    frame[idx++] = len;
    
    /* Calculate CRC starting with cmd and len */
    crc = cmd ^ len;
    
    /* Add data */
    for (uint8_t i = 0; i < len; i++)
    {{
        frame[idx++] = data[i];
        crc ^= data[i];
    }}
    
    frame[idx++] = crc;
    frame[idx++] = FRAME_ETX;
    
    return HAL_UART_Transmit(&{handle}, frame, idx, 100);
}}
'''

    # =========================================================================
    # MAIN.C EXAMPLE GENERATION
    # =========================================================================
    
    def generate_main_example(self) -> str:
        """Generate example main.c usage code"""
        code = '''/* ============================================================================
 * UART USAGE EXAMPLE - Add to main.c
 * ============================================================================
 * 
 * This shows how to use the generated UART driver in your main loop.
 * Copy the relevant parts into your main.c file.
 * ============================================================================
 */

/* 1. Include the header at the top of main.c */
#include "usart.h"

/* 2. In main(), after MX_xxx_Init() calls, initialize UART */
'''
        code += f'// MX_{self.config.uart_instance}_UART_Init();  // Already called if using CubeMX\n'
        
        code += '''
/* 3. In the main while(1) loop, add: */

while (1)
{
    /* Process incoming UART data (non-blocking) */
    UART_Process();
    
    /* Check if a complete frame was received */
    if (UART_IsFrameReady())
    {
'''
        
        if self.config.frame_type == FrameType.TEXT:
            code += '''        uint16_t len;
        uint8_t *data = UART_GetData(&len);
        
        /* Example: Echo back with prefix */
        UART_TransmitString("Received: ");
        UART_Transmit(data, len);
        UART_TransmitString("\\r\\n");
        
        /* Example: Command parsing */
        if (strcmp((char*)data, "LED ON") == 0)
        {
            // HAL_GPIO_WritePin(LED_GPIO_Port, LED_Pin, GPIO_PIN_SET);
            UART_TransmitString("LED is ON\\r\\n");
        }
        else if (strcmp((char*)data, "LED OFF") == 0)
        {
            // HAL_GPIO_WritePin(LED_GPIO_Port, LED_Pin, GPIO_PIN_RESET);
            UART_TransmitString("LED is OFF\\r\\n");
        }
        else if (strcmp((char*)data, "STATUS") == 0)
        {
            UART_TransmitString("System OK\\r\\n");
        }
'''
        elif self.config.frame_type == FrameType.COMMAND:
            code += '''        UART_CommandFrame_t *frame = UART_GetCommandFrame();
        
        if (frame->valid)
        {
            /* Process command based on CMD byte */
            switch (frame->cmd)
            {
                case 0x01:  /* Example: LED Control */
                    if (frame->len >= 1)
                    {
                        if (frame->data[0] == 0x01)
                        {
                            // HAL_GPIO_WritePin(LED_GPIO_Port, LED_Pin, GPIO_PIN_SET);
                        }
                        else
                        {
                            // HAL_GPIO_WritePin(LED_GPIO_Port, LED_Pin, GPIO_PIN_RESET);
                        }
                    }
                    /* Send ACK */
                    UART_SendCommand(0x81, NULL, 0);
                    break;
                    
                case 0x02:  /* Example: Read sensor */
                    {
                        uint8_t response[2] = {0x12, 0x34};  /* Example data */
                        UART_SendCommand(0x82, response, 2);
                    }
                    break;
                    
                case 0x10:  /* Example: Echo */
                    UART_SendCommand(0x90, frame->data, frame->len);
                    break;
                    
                default:
                    /* Unknown command - send NACK */
                    {
                        uint8_t err = 0xFF;
                        UART_SendCommand(0x00, &err, 1);
                    }
                    break;
            }
        }
'''
        else:  # BINARY
            code += f'''        uint16_t len;
        uint8_t *data = UART_GetData(&len);
        
        /* Process {self.config.binary_frame_length}-byte frame */
        /* Example: First byte is command, rest is data */
        uint8_t cmd = data[0];
        
        switch (cmd)
        {{
            case 0x01:
                /* Handle command 0x01 */
                break;
            case 0x02:
                /* Handle command 0x02 */
                break;
            default:
                break;
        }}
        
        /* Echo back the frame */
        UART_Transmit(data, len);
'''
        
        code += '''        
        /* Clear buffer for next frame */
        UART_ClearBuffer();
    }
    
    /* Your other application code here */
}

/* ============================================================================
 * END OF EXAMPLE
 * ============================================================================ */
'''
        return code

    # =========================================================================
    # GENERATE ALL FILES
    # =========================================================================
    
    def generate_all(self, output_dir: str) -> dict:
        """Generate all code files and return as dictionary"""
        files = {
            'usart.h': self.generate_usart_h(),
            'usart.c': self.generate_usart_c(),
            'main_example.c': self.generate_main_example()
        }
        return files
    
    def save_all(self, output_dir: str):
        """Save all generated files to directory"""
        os.makedirs(output_dir, exist_ok=True)
        files = self.generate_all(output_dir)
        
        for filename, content in files.items():
            filepath = os.path.join(output_dir, filename)
            with open(filepath, 'w') as f:
                f.write(content)
            print(f"  ✓ Generated: {filepath}")


# =============================================================================
# CLI INTERFACE
# =============================================================================

def clear_screen():
    os.system('clear' if os.name != 'nt' else 'cls')


def print_banner():
    print("""
╔═══════════════════════════════════════════════════════════════════════════════╗
║                                                                               ║
║   ██╗   ██╗ █████╗ ██████╗ ████████╗     ██████╗ ███████╗███╗   ██╗          ║
║   ██║   ██║██╔══██╗██╔══██╗╚══██╔══╝    ██╔════╝ ██╔════╝████╗  ██║          ║
║   ██║   ██║███████║██████╔╝   ██║       ██║  ███╗█████╗  ██╔██╗ ██║          ║
║   ██║   ██║██╔══██║██╔══██╗   ██║       ██║   ██║██╔══╝  ██║╚██╗██║          ║
║   ╚██████╔╝██║  ██║██║  ██║   ██║       ╚██████╔╝███████╗██║ ╚████║          ║
║    ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝        ╚═════╝ ╚══════╝╚═╝  ╚═══╝          ║
║                                                                               ║
║              STM32 HAL UART Code Generator - Mimic Project                    ║
╚═══════════════════════════════════════════════════════════════════════════════╝
""")


def get_choice(prompt: str, options: list, default: int = 0) -> int:
    """Get user choice from a list of options"""
    print(f"\n{prompt}")
    for i, opt in enumerate(options):
        marker = " [default]" if i == default else ""
        print(f"  {i + 1}. {opt}{marker}")
    
    while True:
        try:
            choice = input(f"\nEnter choice (1-{len(options)}) [default={default+1}]: ").strip()
            if not choice:
                return default
            idx = int(choice) - 1
            if 0 <= idx < len(options):
                return idx
            print(f"Please enter a number between 1 and {len(options)}")
        except ValueError:
            print("Invalid input. Please enter a number.")


def get_int(prompt: str, default: int, min_val: int = 0, max_val: int = 10000000) -> int:
    """Get integer input from user"""
    while True:
        try:
            value = input(f"{prompt} [default={default}]: ").strip()
            if not value:
                return default
            val = int(value)
            if min_val <= val <= max_val:
                return val
            print(f"Please enter a value between {min_val} and {max_val}")
        except ValueError:
            print("Invalid input. Please enter a number.")


def get_string(prompt: str, default: str) -> str:
    """Get string input from user"""
    value = input(f"{prompt} [default={default}]: ").strip()
    return value if value else default


def run_cli():
    """Run the interactive CLI"""
    clear_screen()
    print_banner()
    
    config = UARTConfig()
    
    # UART Instance
    instances = ["USART1", "USART2", "USART6", "UART4", "UART5"]
    idx = get_choice("Select UART Instance:", instances, default=1)
    config.uart_instance = instances[idx]
    
    # Baud Rate
    baud_rates = [9600, 19200, 38400, 57600, 115200, 230400, 460800, 921600]
    print(f"\nCommon baud rates: {', '.join(map(str, baud_rates))}")
    config.baud_rate = get_int("Enter Baud Rate", default=9600, min_val=300, max_val=3000000)
    
    # Parity
    parity_options = ["None", "Even", "Odd"]
    idx = get_choice("Select Parity:", parity_options, default=0)
    config.parity = [Parity.NONE, Parity.EVEN, Parity.ODD][idx]
    
    # Stop Bits
    stop_options = ["1 Stop Bit", "2 Stop Bits"]
    idx = get_choice("Select Stop Bits:", stop_options, default=0)
    config.stop_bits = [StopBits.ONE, StopBits.TWO][idx]
    
    # Frame Type
    frame_options = [
        "Text (delimiter-based: \\n, \\r)",
        "Command (TLV: STX|CMD|LEN|DATA|CRC|ETX)",
        "Binary (fixed-length frame)"
    ]
    idx = get_choice("Select Frame Type:", frame_options, default=0)
    config.frame_type = [FrameType.TEXT, FrameType.COMMAND, FrameType.BINARY][idx]
    
    # Frame-specific options
    if config.frame_type == FrameType.BINARY:
        config.binary_frame_length = get_int("Enter Binary Frame Length (bytes)", default=16, min_val=1, max_val=256)
    
    # Buffer size
    config.max_buffer_size = get_int("Enter Max Buffer Size", default=128, min_val=16, max_val=1024)
    
    # Output directory
    print("\n" + "=" * 60)
    default_dir = "./generated_uart"
    output_dir = get_string("Output Directory", default_dir)
    
    # Summary
    print("\n" + "=" * 60)
    print("CONFIGURATION SUMMARY")
    print("=" * 60)
    print(f"  UART Instance:     {config.uart_instance}")
    print(f"  Baud Rate:         {config.baud_rate}")
    print(f"  Parity:            {config.parity.value}")
    print(f"  Stop Bits:         {config.stop_bits.value}")
    print(f"  Frame Type:        {config.frame_type.value}")
    if config.frame_type == FrameType.BINARY:
        print(f"  Frame Length:      {config.binary_frame_length} bytes")
    print(f"  Buffer Size:       {config.max_buffer_size} bytes")
    print(f"  Output Directory:  {output_dir}")
    print("=" * 60)
    
    # Confirm
    confirm = input("\nGenerate code? (Y/n): ").strip().lower()
    if confirm and confirm != 'y':
        print("Cancelled.")
        return
    
    # Generate
    print("\nGenerating code...")
    generator = UARTCodeGenerator(config)
    generator.save_all(output_dir)
    
    print("\n" + "=" * 60)
    print("✓ CODE GENERATION COMPLETE!")
    print("=" * 60)
    print(f"\nGenerated files in: {os.path.abspath(output_dir)}")
    print("\nNext steps:")
    print("  1. Copy usart.h to Core/Inc/")
    print("  2. Copy usart.c to Core/Src/")
    print("  3. See main_example.c for usage in main.c")
    print("  4. Rebuild with 'make flash'")
    print("\n")


def run_quick_generate(args):
    """Quick generation with command line arguments"""
    # Parse simple args
    config = UARTConfig()
    
    i = 0
    while i < len(args):
        arg = args[i]
        if arg in ['--uart', '-u'] and i + 1 < len(args):
            config.uart_instance = args[i + 1].upper()
            i += 2
        elif arg in ['--baud', '-b'] and i + 1 < len(args):
            config.baud_rate = int(args[i + 1])
            i += 2
        elif arg in ['--parity', '-p'] and i + 1 < len(args):
            p = args[i + 1].upper()
            config.parity = {'NONE': Parity.NONE, 'EVEN': Parity.EVEN, 'ODD': Parity.ODD}.get(p, Parity.NONE)
            i += 2
        elif arg in ['--stop', '-s'] and i + 1 < len(args):
            config.stop_bits = StopBits.TWO if args[i + 1] == '2' else StopBits.ONE
            i += 2
        elif arg in ['--frame', '-f'] and i + 1 < len(args):
            f = args[i + 1].upper()
            config.frame_type = {'TEXT': FrameType.TEXT, 'COMMAND': FrameType.COMMAND, 'BINARY': FrameType.BINARY}.get(f, FrameType.TEXT)
            i += 2
        elif arg in ['--output', '-o'] and i + 1 < len(args):
            output_dir = args[i + 1]
            i += 2
        elif arg in ['--help', '-h']:
            print_usage()
            return
        else:
            i += 1
    
    output_dir = output_dir if 'output_dir' in dir() else './generated_uart'
    
    print(f"Generating UART code for {config.uart_instance} @ {config.baud_rate} baud...")
    generator = UARTCodeGenerator(config)
    generator.save_all(output_dir)
    print(f"Done! Files saved to {output_dir}")


def print_usage():
    print("""
UART Code Generator for STM32 HAL

Usage:
  python UART_Generator.py              # Interactive mode
  python UART_Generator.py [options]    # Quick mode

Options:
  -u, --uart <USART1|USART2|...>   UART instance (default: USART2)
  -b, --baud <rate>                 Baud rate (default: 9600)
  -p, --parity <NONE|EVEN|ODD>      Parity (default: NONE)
  -s, --stop <1|2>                  Stop bits (default: 1)
  -f, --frame <TEXT|COMMAND|BINARY> Frame type (default: TEXT)
  -o, --output <dir>                Output directory (default: ./generated_uart)
  -h, --help                        Show this help

Examples:
  python UART_Generator.py
  python UART_Generator.py -u USART2 -b 115200 -f COMMAND -o ./Core
  python UART_Generator.py --uart USART1 --baud 9600 --frame TEXT
""")


# =============================================================================
# MAIN ENTRY POINT
# =============================================================================

if __name__ == "__main__":
    if len(sys.argv) > 1:
        if sys.argv[1] in ['--help', '-h']:
            print_usage()
        else:
            run_quick_generate(sys.argv[1:])
    else:
        run_cli()
